Default: &defaults
  database: heblab.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: heblab_test.sqlite3
  <<: *defaults

Staging:
  database: heblab_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: heblab_production.sqlite3
  poolsize: 100
  <<: *defaults
